package com.clinicaapp.model.enums;
public enum RazaPerro {
    LABRADOR_RETRIEVER, PASTOR_ALEMAN, GOLDEN_RETRIEVER, BULLDOG_FRANCES, BULLDOG, 
    POODLE, BEAGLE, ROTTWEILER, BRACO_ALEMAN, CORGI, DACHSHUND, YORKSHIRE_TERRIER, 
    AUSSIDOR, BOXER, HUSKY_SIBERIANO, CAESAR, GRAN_DANES, DOBERMAN, PUG, CHIHUAHUA, 
    SHIH_TZU, BORDER_COLLIE, POMERANIA, HABANERO, PIT_BULL, BOSTON_TERRIER, 
    SHIBA_INU, MALTES, CHOW_CHOW, OTRO
}
