package com.clinicaapp.model.enums;

public enum RazaGato {
    SIAMES, PERSA, MAINE_COON, BENGALA, RAGDOLL, ESFINGE, ABISINIO, AZUL_RUSO, 
    BIRMANO, BURMES, CHARTREUX, EXOTICO, HIMALAYO, MANX, MUNCHKIN, BOSQUE_NORUEGA, 
    OCICAT, ORIENTAL, SCOTTISH_FOLD, SELKIRK_REX, SOMALI, TONKINES, TOYGER, 
    ANGORA_TURCO, SABANNAH, OTRO
}